version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"
  npm-registry-npm-goodeggs-com:
    type: npm-registry
    url: https://npm.goodeggs.com
    token: "${{secrets.NPM_REGISTRY_NPM_GOODEGGS_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 27
  registries:
  - npm-registry-registry-npmjs-org
  - npm-registry-npm-goodeggs-com
